<?php

namespace MVC;

class Router
{
    public $rutas_get = [];
    public $rutas_post = [];

    public function __construct()
    {
        
    }   // Here End Construct

    public function comprobarRutas()
    {
        $url_actual = $_SERVER['PATH_INFO'] ?? '/';
        $metodo = $_SERVER['REQUEST_METHOD'];

        if($metodo == 'GET')
        {
            $funcion = $this->rutas_get[$url_actual] ?? null;
        }   // Here End If
        elseif($metodo == 'POST')
        {
            $funcion = $this->rutas_post[$url_actual] ?? null;
        }   // Here End ElseIf

        if($funcion)
        {
            // Call a Function That is Unknown Until Execution Time
            call_user_func( $funcion, $this);
        }   // Here End If
        else
        {
            echo "Pagina No Encontrada";
        }   // Here End Else

    }   // Here End Function

    public function get($url, $funcion)
    {
        $this->rutas_get[$url] = $funcion;
    }   // Here End Function

    public function post($url, $funcion)
    {
        $this->rutas_post[$url] = $funcion;
    }   // Here End Function

    public function render($view, $datos = [])
    {
        foreach ($datos as $key => $value)
        {
            $$key = $value;
        }

        // Capture the output generated by a PHP script before it is sent to the user's browser
        ob_start();
        
        include __DIR__ . "/views/$view.php";
        
        $contenido = ob_get_clean();

        include __DIR__ . "/views/layout.php";
    }   // Here End Function

}   // Here End Class


?>